In [1]:
print("hello world")

hello world


In [3]:
#Deep learning inspired by how the human brain learns 
#Neural networks are a set of algorithms, modeled loosely after the human brain 

In [4]:
#Pytorch Sensor # Similar to array or matrix 
#Tensors are the building blocks of deep learning

In [5]:
import torch
my_list = [[1,2,3],[4,5,6]]
my_tensor = torch.tensor(my_list)
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
my_list = [[1,2,3],[4,5,6]]
my_tensor = torch.tensor(my_list)
print(my_tensor.shape)
print(my_tensor.dtype)
print(my_tensor.device)

torch.Size([2, 3])
torch.int64
cpu


In [ ]:
import torch 
a = torch.tensor([[1,1], [2,2]])
b = torch.tensor([[2,2], [3,3]])
result = a * b 
print(result)
# row * column 

tensor([[2, 2],
        [6, 6]])


In [3]:
# First neural network in pytorch tensors 
''' Neural network consisto of input output and hidden layers 
    Input layer : dataset features 
    Ouput layer : predictions 
    Hidden layers : They lie between input and output layers and consist of various hidden layers 
'''


' Neural network consisto of input output and hidden layers \n    Input layer : dataset features \n    Ouput layer : predictions \n    Hidden layers : They lie between input and output layers and consist of various hidden layers \n'

In [4]:
# Importing as nn to avovid writing as torch.nn and 
# Input neurons : features in our dataset 
# Output : number of classes we watn to rpredit 

In [8]:
import torch
import torch.nn as nn

# Creating input_tensor with three features
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])  # Note the double square brackets

# Defining the linear layer as it applies a linear transformation to the incoming data
linear_layer = nn.Linear(
    in_features=3,
    out_features=2
)

# Passing the input through the linear layer
output = linear_layer(input_tensor)
print(output)
print(linear_layer.weight)
print(linear_layer.bias)

# Weight reflects the importance of different features 
# bias provides neuron iwth a baseline output 

tensor([[0.1981, 0.3240]], grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([[-0.0747, -0.0305,  0.3228],
        [-0.2709,  0.2250, -0.4945]], requires_grad=True)
Parameter containing:
tensor([0.3139, 0.1992], requires_grad=True)


In [10]:
''' Example for linear prediction using weight and bias 
Suppose we are having the 3 inputs having temrpeature humidity and wind and the output of 2 then the 
humidity will have the more significant weight to predict whether it will be cloudy or sunny 


'''

' Example for linear prediction using weight and bias \nSuppose we are having the 3 inputs having temrpeature humidity and wind and the output of 2 then the \nhumidity will have the more significant weight to predict whether it will be cloudy or sunny \n\n\n'

In [11]:
import torch.nn as nn

# Define the number of input features
n_features = 10  # Replace with the actual number of features in your data

# Define the number of output classes
n_classes = 3   # Replace with the actual number of classes in your task

# Creating the network with three linear layers
model = nn.Sequential(
    nn.Linear(n_features, 8),
    nn.Linear(8, 4),
    nn.Linear(4, n_classes)
)

print(model)

Sequential(
  (0): Linear(in_features=10, out_features=8, bias=True)
  (1): Linear(in_features=8, out_features=4, bias=True)
  (2): Linear(in_features=4, out_features=3, bias=True)
)


In [12]:
model = nn.Sequential(nn.Linear(8,4), nn.Linear(4,2))
# First layer has 4 neurons and each neuron has 8+ 1 9 parameters and 9 *4 = 36 parameters 
total = 0 
for parameter in model.parameters():
    total  = total + parameter.numel()
print(total)

46
