In [1]:
print("hello world")

hello world


In [3]:
#Deep learning inspired by how the human brain learns 
#Neural networks are a set of algorithms, modeled loosely after the human brain 

In [4]:
#Pytorch Sensor # Similar to array or matrix 
#Tensors are the building blocks of deep learning

In [5]:
import torch
my_list = [[1,2,3],[4,5,6]]
my_tensor = torch.tensor(my_list)
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
my_list = [[1,2,3],[4,5,6]]
my_tensor = torch.tensor(my_list)
print(my_tensor.shape)
print(my_tensor.dtype)
print(my_tensor.device)

torch.Size([2, 3])
torch.int64
cpu


In [ ]:
import torch 
a = torch.tensor([[1,1], [2,2]])
b = torch.tensor([[2,2], [3,3]])
result = a * b 
print(result)
# row * column 

tensor([[2, 2],
        [6, 6]])


In [3]:
# First neural network in pytorch tensors 
''' Neural network consisto of input output and hidden layers 
    Input layer : dataset features 
    Ouput layer : predictions 
    Hidden layers : They lie between input and output layers and consist of various hidden layers 
'''


' Neural network consisto of input output and hidden layers \n    Input layer : dataset features \n    Ouput layer : predictions \n    Hidden layers : They lie between input and output layers and consist of various hidden layers \n'

In [4]:
# Importing as nn to avovid writing as torch.nn and 
# Input neurons : features in our dataset 
# Output : number of classes we watn to rpredit 

In [8]:
import torch
import torch.nn as nn

# Creating input_tensor with three features
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])  # Note the double square brackets

# Defining the linear layer as it applies a linear transformation to the incoming data
linear_layer = nn.Linear(
    in_features=3,
    out_features=2
)

# Passing the input through the linear layer
output = linear_layer(input_tensor)
print(output)
print(linear_layer.weight)
print(linear_layer.bias)

# Weight reflects the importance of different features 
# bias provides neuron iwth a baseline output 

tensor([[0.1981, 0.3240]], grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([[-0.0747, -0.0305,  0.3228],
        [-0.2709,  0.2250, -0.4945]], requires_grad=True)
Parameter containing:
tensor([0.3139, 0.1992], requires_grad=True)


In [10]:
''' Example for linear prediction using weight and bias 
Suppose we are having the 3 inputs having temrpeature humidity and wind and the output of 2 then the 
humidity will have the more significant weight to predict whether it will be cloudy or sunny 


'''

' Example for linear prediction using weight and bias \nSuppose we are having the 3 inputs having temrpeature humidity and wind and the output of 2 then the \nhumidity will have the more significant weight to predict whether it will be cloudy or sunny \n\n\n'

In [11]:
import torch.nn as nn

# Define the number of input features
n_features = 10  # Replace with the actual number of features in your data

# Define the number of output classes
n_classes = 3   # Replace with the actual number of classes in your task

# Creating the network with three linear layers
model = nn.Sequential(
    nn.Linear(n_features, 8),
    nn.Linear(8, 4),
    nn.Linear(4, n_classes)
)

print(model)

Sequential(
  (0): Linear(in_features=10, out_features=8, bias=True)
  (1): Linear(in_features=8, out_features=4, bias=True)
  (2): Linear(in_features=4, out_features=3, bias=True)
)


In [12]:
model = nn.Sequential(nn.Linear(8,4), nn.Linear(4,2))
# First layer has 4 neurons and each neuron has 8+ 1 9 parameters and 9 *4 = 36 parameters 
total = 0 
for parameter in model.parameters():
    total  = total + parameter.numel()
print(total)

46


In [ ]:
''' Activity functions added non-linearty to the network 
    Sigmode for binary classification 
    Softmax for multi class classification 
    Suppose we are trying to know whether we have mamal or not we have 3 input layers limbs eggs hair and then 
    4 linear layers there 
     ''' 

' Activity functions added non-linearty to the network \n    Sigmode for binary classification \n    Softmax for multi class classification \n    Suppose we are trying to know whether we have mamal or not we have 3 input layers limbs eggs hair and then \n'

In [2]:
import torch 
import torch.nn as nn 

input_tensor = torch.tensor([[6]])
sigmoid = nn.Sigmoid()
output = sigmoid(input_tensor)
print(output)

'''Sigmoid is an activation function used in binary classification (e.g., yes/no predictions).

It converts logits (raw model outputs) into probabilities.

Output range: (0, 1) (useful for probabilities).

Example use case: Final layer in a binary classifier (e.g., spam detection).'''

tensor([[0.9975]])


'Sigmoid is an activation function used in binary classification (e.g., yes/no predictions).\n\nIt converts logits (raw model outputs) into probabilities.\n\nOutput range: (0, 1) (useful for probabilities).\n\nExample use case: Final layer in a binary classifier (e.g., spam detection).'

In [4]:
'''
 1.0 |        *
     |       *
     |      *
     |     *
0.5 |----*---------
     |   *
     |  *
     | *
0.0 +----------------
      -6  0  6            '''

'\n 1.0 |        *\n     |       *\n     |      *\n     |     *\n0.5 |----*---------\n     |   *\n     |  *\n     | *\n0.0 +----------------\n      -6  0  6            '

In [5]:
import torch 
import torch.nn as nn 

# 1. Create a 1x3 tensor (3 raw scores/logits for 3 classes)
input_tensor = torch.tensor([[4.3, 6.1, 2.3]])

# 2. Initialize Softmax (dim=-1 applies it to the last dimension)
probabilities = nn.Softmax(dim=-1)

# 3. Apply Softmax to convert logits to probabilities
output_tensor = probabilities(input_tensor)

# 4. Print the result
print(output_tensor)

tensor([[0.1392, 0.8420, 0.0188]])


In [6]:
'''
Concept	Key Takeaway
Softmax	Converts logits to probabilities for multi-class problems. Sums to 1.
Sigmoid	Used for binary classification. Outputs independent probabilities (0 to 1).
Use Case	Use Softmax for >2 classes, Sigmoid for 2 classes.
PyTorch	nn.Softmax(dim=1) for probabilities, CrossEntropyLoss for training
 '''

'\nConcept\tKey Takeaway\nSoftmax\tConverts logits to probabilities for multi-class problems. Sums to 1.\nSigmoid\tUsed for binary classification. Outputs independent probabilities (0 to 1).\nUse Case\tUse Softmax for >2 classes, Sigmoid for 2 classes.\nPyTorch\tnn.Softmax(dim=1) for probabilities, CrossEntropyLoss for training\n '

In [ ]:
# Forward passs : input data flows through layers calculations performed at each other 
# Output is based on weights and biases 
# Used for traning and prediction 
# Possible classifications : binary classifications , multi-class classification 

import torch 
import torch.nn as nn 
input_tensor = torch.tensor([[0.1234, 0.5678, 0.9012, 0.3456, 0.7890, 0.2345],
        [0.9876, 0.4321, 0.1098, 0.6789, 0.3210, 0.8765],
        [0.5432, 0.8765, 0.2109, 0.9012, 0.4567, 0.1234],
        [0.7654, 0.2198, 0.5432, 0.1098, 0.8901, 0.3456],
        [0.3210, 0.6543, 0.9876, 0.2345, 0.5678, 0.8901]])

# Suppose we have 5 * 6 shape where there are 5 animals and six features 
# Creating the model using sigmoid function which is used for binary classification 

model = nn.Sequential(
nn.Linear(6 ,4),
nn.Linear(4,1),
nn.Sigmoid() # sigmoid activation function 

)

output = model(input_tensor)
print(output)

''' 
Here, input dimension = 6 (6 features of each animal), output dimension = 4 (4 neurons).
This reduces/expands the feature information — from 6 features into 4 new learned features
nn.Linear(4, 1)
Now the output of first layer (size 4) is passed into another linear layer.
Input = 4, Output = 1.

'''

tensor([[0.5701],
        [0.5795],
        [0.5344],
        [0.5959],
        [0.5879]], grad_fn=<SigmoidBackward0>)


' \nHere, input dimension = 6 (6 features of each animal), output dimension = 4 (4 neurons).\nThis reduces/expands the feature information — from 6 features into 4 new learned features\nnn.Linear(4, 1)\nNow the output of first layer (size 4) is passed into another linear layer.\nInput = 4, Output = 1.\n'

In [ ]:
'''
Why Linear layers?

They learn the relationships between features and outputs.
No non-linearity until activation function is added.

Why Sigmoid?
For binary classification to predict a probability between 0 and 1.
Otherwise (for multiclass classification), you'd use something else like Softmax. '''


"\nWhy Linear layers?:\n\nThey learn the relationships between features and outputs.\n\nNo non-linearity until activation function is added.\n\nWhy Sigmoid?:\n\nFor binary classification to predict a probability between 0 and 1.\n\nOtherwise (for multiclass classification), you'd use something else like Softmax. "

In [5]:
import torch
import torch.nn as nn

''' 
class 1 - mammal 
class 2 - bird 
class 3 - reptile 
'''

n_classes = 3

# Creating the multiclass classification model
model = nn.Sequential(
    nn.Linear(6, 4),    # First Linear layer: input 6 features -> output 4 features
    nn.Linear(4, n_classes),  # Second Linear layer: 4 features -> 3 class scores
    nn.Softmax(dim=-1)  # Softmax activation across the classes
)


'''1. nn.Linear(6, 4)
Input: 6 features (example: weight, size, temperature, etc.)

Output: 4 neurons (abstract features learned by the network).

Purpose:

Transform the raw input into new feature representations.

2. nn.Linear(4, n_classes)
(where n_classes = 3)

Input: 4 features (from the previous layer).

Output: 3 numbers (one for each class: mammal, bird, reptile).

Purpose:

Produce raw scores (called logits) for each class.'''


output = model(input_tensor)
print(output.shape)
print(output)



torch.Size([5, 3])
tensor([[0.1915, 0.3374, 0.4711],
        [0.1678, 0.2989, 0.5333],
        [0.1790, 0.3133, 0.5077],
        [0.1812, 0.3154, 0.5034],
        [0.1718, 0.3356, 0.4927]], grad_fn=<SoftmaxBackward0>)


In [ ]:
# Regression model regression → the output should be a continuous real number, not probabilities.
import torch
import torch.nn as nn

# 11 input features
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Implement a neural network with exactly four linear layers
model = nn.Sequential(
    nn.Linear(11, 64),   # Layer 1: 11 → 64
    nn.Linear(64, 32),   # Layer 2: 64 → 32
    nn.Linear(32, 16),   # Layer 3: 32 → 16
    nn.Linear(16, 1)     # Layer 4: 16 → 1 (regression output)
)

output = model(input_tensor)
print(output)


tensor([[0.6023]], grad_fn=<AddmmBackward0>)
