<a href="https://colab.research.google.com/github/dabster108/Leetcode-DeepLearning-LlM/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np



In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
np.array([5,4,6,5,2])

array([5, 4, 6, 5, 2])

In [ ]:
a = np.array([5,4,6,5,2])
a

array([5, 4, 6, 5, 2])

In [ ]:
a[2] = 10
a

array([ 5,  4, 10,  5,  2])

In [ ]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

Multi dimensional Array

In [ ]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.zeros((1,5))

array([[0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((2,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
n =np.array([
    [1,3,4],
    [15,53,4],
    [11,23,43],

])
n

array([[ 1,  3,  4],
       [15, 53,  4],
       [11, 23, 43]])

In [ ]:
n[0,1] = 20
n

array([[ 1, 20,  4],
       [15, 53,  4],
       [11, 23, 43]])

In [ ]:
n[2] = [1,1,1]
n

array([[ 1, 20,  4],
       [15, 53,  4],
       [ 1,  1,  1]])

In [ ]:
n[:,2] = [0,1,2]
n

array([[ 1, 20,  0],
       [15, 53,  1],
       [ 1,  1,  2]])

In [ ]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [ ]:
np.random.rand(3)

array([0.62113383, 0.52914209, 0.13457995])

In [ ]:
np.random.seed(2)
np.random.randn(5,2)


array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

Element wise Operation

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
b = (10+ (a*2))
b

array([10, 12, 14, 16, 18])

Comparison Operator

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a >=2

array([False, False,  True,  True,  True])

In [ ]:
b

array([10, 12, 14, 16, 18])

In [ ]:
a >b

array([False, False, False, False, False])

Summarizing the Data

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a.std()

1.4142135623730951

In [ ]:
a.min()

0

In [ ]:
a.max();
a

array([0, 1, 2, 3, 4])

In [ ]:
a.sum();

In [ ]:
import numpy as np
import sys

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a[0]

1

In [ ]:
a[0:]


array([1, 2, 3, 4])

In [ ]:
a[1:3]

array([2, 3])

In [ ]:
a[1:-1]

array([2, 3])

In [ ]:
a[::2] #skip

array([1, 3])

In [ ]:
import numpy as np
n =np.array([
    [1,3,4],
    [15,53,4],
    [11,23,43],

])
n.shape
n.size



9

In [ ]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


Broadcasting and Vectorized Operations


In [ ]:
import numpy as np
a = np.arange(4)
print(a)

[0 1 2 3]


In [ ]:
a+10

array([10, 11, 12, 13])

In [ ]:
a * 10


array([ 0, 10, 20, 30])

In [ ]:
a += 100
a


array([200, 201, 202, 203])

In [ ]:
 l = [ 0 , 1 , 2 ,3 ]
 [i * 10 for i in l]

[0, 10, 20, 30]

In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
b = np.array([10,10,10,10])
b

array([10, 10, 10, 10])

In [ ]:
a +b


array([10, 11, 12, 13])

In [ ]:
a * b


array([ 0, 10, 20, 30])

In [ ]:
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

Boolean Arrays

In [ ]:
import numpy as np
a  = np.arange(4)

In [ ]:
a >=2

array([False, False,  True,  True])

In [ ]:
a.mean() > 3

np.False_

In [ ]:
a[a>=2]

array([2, 3])

In [ ]:
a[a >= a.mean()]

array([2, 3])

In [ ]:
import numpy as np
A = np.random.randint(100, size=(3, 3))  # Generates a 3x3 matrix with random integers from 0 to 99
print(A)

[[43 35 13]
 [89 10 62]
 [62 89  8]]


In [ ]:
A > 30

array([[ True,  True, False],
       [ True, False,  True],
       [ True,  True, False]])

In [ ]:
A[A > 33]


array([43, 35, 89, 62, 62, 89])

Linear Algebra

In [ ]:
import numpy as np

a = np.array([
    [43, 35, 13],
    [89, 10, 62],
    [62, 89, 8]
])

print(a)
print(" ")
b = np.random.randint(22, size =( 3 , 3 ))
print(b)

[[43 35 13]
 [89 10 62]
 [62 89  8]]
 
[[12 10 18]
 [ 6  5  5]
 [13 12  6]]


In [ ]:
a.dot(b)


array([[ 895,  761, 1027],
       [1934, 1684, 2024],
       [1382, 1161, 1609]])

In [ ]:
b.T

array([[12,  6, 13],
       [10,  5, 12],
       [18,  5,  6]])

In [ ]:
a.T.dot(b.T)

array([[2522, 1013, 1999],
       [2122,  705, 1109],
       [ 920,  428,  961]])

Size of Objects in Memory

In [ ]:
import sys

print(sys.getsizeof(1))  # Get the size of an integer


28


In [ ]:
import numpy as np
import time

# Using a NumPy array
arr = np.arange(1_000_000)
start = time.time()
arr = arr * 2  # Vectorized operation
print("NumPy time:", time.time() - start)

# Using a Python list
lst = list(range(1_000_000))
start = time.time()
lst = [x * 2 for x in lst]  # Loop-based operation
print("Python list time:", time.time() - start)


NumPy time: 0.005339145660400391
Python list time: 0.06345510482788086


## Differences Between NumPy Arrays and Python Lists  

| Feature           | NumPy Array (`nparray`) | Python List |
|------------------|----------------------|-------------|
| **Memory Efficiency** | Uses a **contiguous** block of memory, requiring **less space** | Stores elements as **individual objects**, taking **more memory** |
| **Performance** | **Faster** due to optimized C-based implementation | **Slower** because of dynamic typing and memory overhead |
| **Operations** | Supports **vectorized operations** (faster calculations) | Requires manual loops for element-wise operations (slower) |
| **Data Type** | Elements must be of the **same data type** (int, float, etc.) | Can store **mixed data types** |
| **Built-in Functions** | Provides **powerful mathematical operations** | Limited built-in support for numerical computations |



In [ ]:
import pandas as pd
import numpy as np


In [ ]:
# In millions
g7_pop = pd.Series([35.467, 63.951, 80.940, 60.665, 127.061, 64.511, 318.523])

In [ ]:
g7_pop = pd.Series([35.467, 63.951, 80.940, 60.665, 127.061, 64.511, 318.523])
g7_pop

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
dtype: float64

In [ ]:
g7_pop[0]

np.float64(35.467)

In [ ]:
g7_pop.index


RangeIndex(start=0, stop=7, step=1)

In [ ]:
l = ['a', 'b', 'c']

In [ ]:
g7_pop.index = [ # keeping the index as the value given here
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States',
]

In [ ]:
g7_pop[1]

<ipython-input-12-fd7076683bd9>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  g7_pop[1]


np.float64(63.951)

In [ ]:
g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
dtype: float64

In [ ]:
pd.Series({
    'Canada': 35.467,
    'France': 63.951,
    'Germany': 80.94,
    'Italy': 60.665,
    'Japan': 127.061,
    'United Kingdom': 64.511,
    'United States': 318.523
}, name='G7 Population in millions')

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

Pandas Indexing and Conditional Selection

In [ ]:
import pandas as pd
pd.Series(
    [35.467, 63.951, 80.94, 60.665, 127.061, 64.511, 318.523],
    index=['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom',
       'United States'],
    name='G7 Population in millions')

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: G7 Population in millions, dtype: float64

In [ ]:
pd.Series(g7_pop, index=['France', 'Germany', 'Italy', 'Spain'])

France     63.951
Germany    80.940
Italy      60.665
Spain         NaN
dtype: float64


Indexing
Indexing works similarly to lists and dictionaries, you use the index of the element you're looking

In [ ]:
g7_pop


Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
dtype: float64

In [ ]:
g7_pop['Canada']

np.float64(35.467)

In [ ]:
#Numeric positions can also be used, with the iloc attribute
g7_pop.iloc[0]

np.float64(35.467)

In [ ]:
g7_pop[['Italy', 'France']]

Italy     60.665
France    63.951
dtype: float64

In [ ]:
g7_pop.iloc[[0, 1]]

Canada    35.467
France    63.951
dtype: float64

In [ ]:
g7_pop['Canada': 'Italy']  #from canada to italy

Canada     35.467
France     63.951
Germany    80.940
Italy      60.665
dtype: float64

In [ ]:
#conditional selection
g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
dtype: float64

In [ ]:
g7_pop > 70 # shows boolean expression

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
dtype: bool

In [ ]:
g7_pop[g7_pop > 70] # shows which values are greater

Germany           80.940
Japan            127.061
United States    318.523
dtype: float64

In [ ]:
g7_pop.mean() # mean of the group of seven g7_pop.std()

np.float64(107.30257142857144)

In [ ]:
g7_pop[g7_pop > g7_pop.mean()] # values which are greater than the mean

Japan            127.061
United States    318.523
dtype: float64

In [ ]:
g7_pop.std()

97.24996987121581

In [ ]:
''' ~ not
| or
& and '''


' ~ not\n| or\n& and '

In [ ]:
g7_pop['France': 'Italy'].mean()

np.float64(68.51866666666666)

Operations and Methods

In [ ]:
g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
dtype: float64

In [ ]:
g7_pop * 10000

Canada             354670.0
France             639510.0
Germany            809400.0
Italy              606650.0
Japan             1270610.0
United Kingdom     645110.0
United States     3185230.0
dtype: float64

In [ ]:
g7_pop.mean()

np.float64(107.30257142857144)

In [ ]:
import numpy as np
np.log(g7_pop)


Canada            3.568603
France            4.158117
Germany           4.393708
Italy             4.105367
Japan             4.844667
United Kingdom    4.166836
United States     5.763695
dtype: float64

In [ ]:
g7_pop['France' : 'Italy'].mean()

np.float64(68.51866666666666)

In [ ]:
g7_pop['Canada'] = 40.5

In [ ]:
g7_pop.iloc[-1] = 500


In [ ]:
g7_pop

Canada             40.500
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     500.000
dtype: float64

In [ ]:
g7_pop[g7_pop < 70]

Canada            40.500
France            63.951
Italy             60.665
United Kingdom    64.511
dtype: float64

In [ ]:
import numpy as np
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Output:
# [[ 1  2  20  4  5]
# [ 6  7 20  9 10]]

In [ ]:
#Mathematics
import numpy as np
a = np.array([1,2,3,4])
a+2

array([3, 4, 5, 6])

In [ ]:
a = np.ones((2,4))
print(a)
b  = np.full((3,2), 2)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [ ]:
a = np.ones((2,3))
print(a)
b  = np.full((3,2), 2)
print(b)
c  = np.matmul(a,b)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [ ]:
#Find the determinanat
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [ ]:
stats = np.array(([1,2,3], [4,5,6]))
stats


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
stats = np.array(([1,2,3], [4,5,6]))
stats
np.max(stats, axis = 0 )

array([4, 5, 6])

In [ ]:
# Rearranzing arrays
before  = np.array(([1,2,3,4], [5,6,7,8]))
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#vertically stacking the a and b
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.vstack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Loading data and advanced Indexing


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])

# Correcting the indexing
print(a[[1,2,8]])  # Output: [2 3 9]
# indexig
# For 2d array[row,column]

import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(a)



[2 3 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [1]:
#a[start_row:end_row, start_col:end_col]


In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Sample movie data
import pandas as pd

data = {
    'movie_id': list(range(1, 51)),
    'title': [
        "The Matrix", "John Wick", "Toy Story", "The Lord of the Rings", "The Lion King",
        "Inception", "Interstellar", "Gladiator", "Titanic", "Avatar",
        "The Dark Knight", "Pulp Fiction", "Fight Club", "Forrest Gump", "The Shawshank Redemption",
        "The Godfather", "The Avengers", "Jurassic Park", "Star Wars", "Back to the Future",
        "The Silence of the Lambs", "Saving Private Ryan", "Schindler's List", "Braveheart", "Casablanca",
        "Goodfellas", "The Departed", "Whiplash", "La La Land", "The Prestige",
        "The Social Network", "Guardians of the Galaxy", "Deadpool", "The Hunger Games", "Mad Max: Fury Road",
        "Black Panther", "Wonder Woman", "Spider-Man", "Iron Man", "Doctor Strange",
        "The Incredibles", "Finding Nemo", "Monsters, Inc.", "Up", "Inside Out",
        "Coco", "Frozen", "Moana", "Zootopia", "Ratatouille"
    ],
    'description': [
        "A computer hacker discovers reality is a simulation controlled by machines.",
        "An ex-hitman comes out of retirement to seek revenge on gangsters.",
        "Toys come to life and embark on adventures in a child's room.",
        "A hobbit's quest to destroy a powerful ring threatens Middle-earth.",
        "A lion cub learns to embrace his destiny as king of the jungle.",
        "A thief who steals corporate secrets through dream-sharing technology.",
        "A team travels through a wormhole to save humanity from extinction.",
        "A Roman general seeks vengeance after his family is murdered.",
        "A tragic love story set aboard the ill-fated Titanic ship.",
        "Humans colonize Pandora, facing a conflict with native inhabitants.",
        "Batman battles the Joker to save Gotham City.",
        "Stories of crime and redemption intersect in unexpected ways.",
        "An insomniac office worker forms an underground fight club.",
        "A man with a low IQ influences many lives with his simple wisdom.",
        "Two imprisoned men bond over years, finding redemption together.",
        "The aging patriarch of a crime family transfers control to his son.",
        "Superheroes team up to save Earth from an alien invasion.",
        "Dinosaurs are brought back to life in a theme park with disastrous results.",
        "A space opera about the battle between the Jedi and Sith.",
        "A teenager travels back in time in a DeLorean car.",
        "A young FBI cadet seeks help from a cannibalistic serial killer.",
        "Allied soldiers undertake a risky mission during World War II.",
        "A businessman saves hundreds during the Holocaust by employing Jews.",
        "A Scottish warrior leads a rebellion against English rule.",
        "A classic romantic drama set in World War II Casablanca.",
        "The rise and fall of a mob associate in New York City.",
        "An undercover cop infiltrates a crime syndicate.",
        "A jazz drummer's intense training leads to self-destruction.",
        "A musician and an actress fall in love in Los Angeles.",
        "Two magicians engage in a dangerous rivalry.",
        "The story of Facebook's founding and legal battles.",
        "A group of space criminals must save the galaxy.",
        "A wisecracking mercenary breaks the fourth wall.",
        "A girl becomes a symbol in a dystopian rebellion.",
        "Post-apocalyptic chase across the desert for survival.",
        "A superhero fights to save his nation and the world.",
        "An Amazon warrior leaves her home to fight in World War I.",
        "A young man becomes the superhero Spider-Man.",
        "An industrialist builds a powered suit to fight evil.",
        "A surgeon learns mystic arts to heal and battle threats.",
        "A family of superheroes fights to save the world.",
        "A clownfish searches for his missing son in the ocean.",
        "Monsters scare kids to generate energy for their city.",
        "An elderly man fulfills a lifelong dream with a young scout.",
        "Emotions inside a young girl's mind guide her through life.",
        "A boy journeys to the Land of the Dead to find his family.",
        "Two sisters struggle with their kingdom's magical curse.",
        "A young navigator sails to save her people and find herself.",
        "Animals live in a city and learn to coexist with humans.",
        "A rat aspires to be a chef in a Parisian restaurant."
    ]
}

df = pd.DataFrame(data)


# Initialize TF-IDF Vectorizer to convert descriptions to TF-IDF matrix
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['description'])

# Function to get user profile vector from movies watched
def create_user_profile(watched_titles, df, tfidf_matrix):
    # Get indices of movies user watched
    indices = []
    for title in watched_titles:
        title = title.strip()
        idx_list = df.index[df['title'].str.lower() == title.lower()].tolist()
        if idx_list:
            indices.append(idx_list[0])
        else:
            print(f"Warning: '{title}' not found in the movie list.")
    if not indices:
        raise ValueError("No valid movie titles found in input.")

    # Extract TF-IDF vectors for watched movies
    watched_vectors = tfidf_matrix[indices]

    # Compute the average vector (user profile)
    user_profile = watched_vectors.mean(axis=0)

    # Convert from numpy.matrix to numpy.ndarray to avoid compatibility issues
    user_profile = user_profile.A

    return user_profile


# Function to recommend movies based on user profile
def recommend_movies(user_profile, df, tfidf_matrix, top_n=3):
    # Compute cosine similarity between user profile and all movie descriptions
    cosine_similarities = cosine_similarity(user_profile, tfidf_matrix).flatten()

    # Show similarity with all movies
    print("\nCosine similarity scores with all movies:")
    for i, score in enumerate(cosine_similarities):
        print(f"{df['title'].iloc[i]}: {score:.4f}")

    # Get indices of top recommended movies (exclude watched movies)
    top_indices = cosine_similarities.argsort()[::-1]

    return top_indices, cosine_similarities

# --- Main interactive flow ---
if __name__ == "__main__":
    watched_input = input("Enter the movie(s) you have watched (comma-separated): ")
    watched_titles = [t.strip() for t in watched_input.split(',')]

    try:
        user_profile = create_user_profile(watched_titles, df, tfidf_matrix)
        print(f"\nUser profile vector shape: {user_profile.shape}")

        top_indices, similarities = recommend_movies(user_profile, df, tfidf_matrix)

        # Filter out the movies already watched
        watched_indices = [df.index[df['title'].str.lower() == t.lower()][0] for t in watched_titles if t.lower() in df['title'].str.lower().values]

        # Recommend top 3 movies not watched yet
        recommendations = [i for i in top_indices if i not in watched_indices][:3]

        print("\nRecommended movies for you:")
        for idx in recommendations:
            print(f"{df['title'].iloc[idx]} (Similarity: {similarities[idx]:.4f})")

    except ValueError as e:
        print(e)


Enter the movie(s) you have watched (comma-separated): Inception

User profile vector shape: (1, 253)

Cosine similarity scores with all movies:
The Matrix: 0.0000
John Wick: 0.0000
Toy Story: 0.0000
The Lord of the Rings: 0.0000
The Lion King: 0.0000
Inception: 1.0000
Interstellar: 0.0000
Gladiator: 0.0000
Titanic: 0.0000
Avatar: 0.0000
The Dark Knight: 0.0000
Pulp Fiction: 0.0000
Fight Club: 0.0000
Forrest Gump: 0.0000
The Shawshank Redemption: 0.0000
The Godfather: 0.0000
The Avengers: 0.0000
Jurassic Park: 0.0000
Star Wars: 0.0000
Back to the Future: 0.0000
The Silence of the Lambs: 0.0000
Saving Private Ryan: 0.0000
Schindler's List: 0.0000
Braveheart: 0.0000
Casablanca: 0.0000
Goodfellas: 0.0000
The Departed: 0.0000
Whiplash: 0.0000
La La Land: 0.0000
The Prestige: 0.0000
The Social Network: 0.0000
Guardians of the Galaxy: 0.0000
Deadpool: 0.0000
The Hunger Games: 0.0000
Mad Max: Fury Road: 0.0000
Black Panther: 0.0000
Wonder Woman: 0.0000
Spider-Man: 0.0000
Iron Man: 0.0000
Doct